name: Deploy Hugo site
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: arc-runner-set
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - name: Install Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "latest"
          extended: true
      - name: Build Hugo Site
        run: hugo --minify
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
      - uses: actions-hub/kubectl@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/hugo-site:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/hugo-site:${{ github.sha }}
      - name: Set up Kubernetes
        uses: azure/setup-kubectl@v2
        with:
          version: "1.25" # Adjust to your Kubernetes version
      - name: Deploy to Kubernetes
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }} # Add KUBECONFIG as a GitHub secret
        run: |
          kubectl set image deployment/hugo-site hugo-site=${{ secrets.DOCKER_USERNAME }}/hugo-site:${{ github.sha }}
          kubectl apply -f deployment.yaml
